### ISSUE TITLE
0.8.1 and 0.8.4 fails to build on Alpine 3.4 x86_64 (FS_ENCRYPT_FL undeclared, V7_ENV undefined)

### ISSUE THREAD

**Issue by rsms** [landley/toybox#254]
Building toybox from source on Alpine linux with instruction in readme (i.e. `make defconfig && make`) fails for both 0.8.4 and 0.8.1 (but with different errors.)

## Repro

Launch an Alpine 3.4 image in docker and install some packages:

```
$ docker run --rm -it alpine:3.4
# in the docker container:
$ apk update && apk add --no-cache \
  binutils make libgcc gcc g++ musl-dev wget ca-certificates \
  linux-headers flex bison tar bash
$ cd
```

Repro for toybox 0.8.4:

```sh
$ wget http://landley.net/toybox/downloads/toybox-0.8.4.tar.gz
# ...
$ tar xf toybox-0.8.4.tar.gz && cd toybox-0.8.4
$ make defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1 \
  -DPROJECT_NAME=\"ToyBox\"
scripts/genconfig.sh
kconfig/conf -D /dev/null Config.in > /dev/null
$ make
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe...........
Make generated/config.h from .config.
generated/flags.h generated/globals.h generated/tags.h generated/help.h
Compile toybox.......................................................................toys/other/lsattr.c:105:37: error: 'FS_ENCRYPT_FL' undeclared here (not in a function)
   {"Encrypted",                     FS_ENCRYPT_FL,      'E'},
                                     ^
toys/other/lsattr.c:113:37: error: 'FS_INLINE_DATA_FL' undeclared here (not in a function)
   {"Inline_Data",                   FS_INLINE_DATA_FL,  'N'},
                                     ^
Makefile:17: recipe for target 'toybox' failed
make: *** [toybox] Error 1
```

Here is the generated Config.in: [Config.in.zip](https://github.com/landley/toybox/files/5719963/Config.in.zip) (had to put it in a zip for github to accept it)

Repro for toybox 0.8.1:

```sh
$ wget http://landley.net/toybox/downloads/toybox-0.8.1.tar.gz
# ...
$ tar xf toybox-0.8.1.tar.gz && cd toybox-0.8.1
$ make defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1 \
  -DPROJECT_NAME=\"ToyBox\"
scripts/genconfig.sh
kconfig/conf -D /dev/null Config.in > /dev/null
$ make
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe...........
Make generated/config.h from .config.
generated/flags.h generated/globals.h generated/tags.h generated/help.h
Compile toybox..........................................................................................................................................toys/posix/getconf.c:139:21: error: '_CS_V7_ENV' undeclared here (not in a function)
 #define CONF(n) {#n,_CS_ ## n}
                     ^
toys/posix/getconf.c:140:15: note: in expansion of macro 'CONF'
   CONF(PATH), CONF(V7_ENV)
               ^
Makefile:19: recipe for target 'toybox' failed
make: *** [toybox] Error 1
```

## Environment

Alpine Linux running in docker (alpine:3.4)

Details:

```sh
$ uname -a
Linux baf84a33e6e6 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 Linux
$ gcc --version
gcc (Alpine 5.3.0) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO [...]
$ sha1sum toybox-0.8.*.tar.gz
4de23d92b6ab9393dd5e3da8135afe7b9d0b9e09  toybox-0.8.1.tar.gz
eff4cb18cf338dc08e15fddc0dd486d8c6fc7311  toybox-0.8.4.tar.gz
```

Installed Alpine packages:

- binutils
- bison
- ca-certificates
- flex
- g++
- gcc
- git
- libgcc
- linux-headers
- make
- musl-dev
- tar
- wget

**Comment by rsms** [comment]
It appears that `FS_ENCRYPT_FL` was added in Linux 4.5 (it's present in fs.h in 4.5 but not in 4.4)

```
$ grep FS_ENCRYPT_FL /usr/include/linux/fs.h
$
```

**Comment by rsms** [comment]
Building toybox on Alpine 3.12 _WORKS_
i.e. change `docker run --rm -it alpine:3.4` to → `docker run --rm -it alpine:3.12` in the repro in the OP and `make` successfully completes for toybox 0.8.4

Idea for a solution: checking if `FS_ENCRYPT_FL` is defined in `lsattr.c` and only care for it if so.

**Comment by landley** [comment]
Commit 4b78acc7bc1a
