### ISSUE TITLE
Can’t compile on Apple Silicon with macOS Monterey

### ISSUE THREAD

**Issue by mcnaugha** [landley/toybox#314]
Apologies if this has been explained elsewhere... I'm new to this...

The AARCH64/ARM64 binary won't run on macOS Monterey 12.x and I can't seem to build it from source either.

Should it be working? Trying to build Android and I think it's dependent on toybox. Can't find a working build of toybox for Apple Silicon anywhere.

Thanks.

**Comment by landley** [comment]
I ship Linux binaries (statically compiled against musl-libc).

Yes it builds on macos, there's a kconfig/macos_defconfig ("make macos_defconfig") with the subset of commands that have been tested there. I don't have a mac build machine and I'm told Apple goes to great lengths to prevent its proprietary OS I haven't bought a copy of from running under qemu (back in the day there was an anti-circumvention signature in the keyboard controller so they could sue people who implemented compatibility...?), so I leave building it to the Android guys, who ship a binary in AOSP: https://android.googlesource.com/platform/prebuilts/build-tools/+/refs/heads/master/darwin-x86/bin/

**Comment by enh-google** [comment]
yeah, looks like the mac build broke recently. (Android wasn't affected because we have our own build system, and i hadn't needed to build locally on a mac since.)

patch sent to mailing list...

**Comment by enh-google** [comment]
> Arm doesn't have an x86 emulator?

there is: it's called "rosetta2".

fwiw, although i don't personally have an M1 mac yet, as soon as someone on my team got one, i asked them to build and test toybox :-) they reported no problems.

as i said in the previous comment, this looks like just a generic darwin build break that i can reproduce on my x86 mac.

it would be nice to have `defconfig` default to `macos_defconfig` on darwin, but judging by the "mentioned this issue" link above, *this* reporter at least made it past that hurdle :-)

**Comment by landley** [comment]
I need to replace the entire kconfig directory. It's on the todo list...

**Comment by xsscx** [comment]
Hey-

Looks fine from here...

Datapoint
-----
For macOS 12.1 (21C52) on either X86_64 or M1 T8101 the most recently Commit https://github.com/landley/toybox/commit/4991ae7261671f00040c85a1c2d2eb39fd6a05ae Builds fine.

```
make macos_defconfig
make
-r-xr-xr-x    1 xss  staff  281720 Jan 10 16:51 toybox
```
uname -a sample
```
21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

Toybox also Builds on macOS 11.6.2 20G314 and 11.6.3 on either X86_64 or M1 T8101

I'm just in the process of updating the iOS for SRD Build Pipeline rolling back to lask known good Commit

Thank you very much for all the effort at your end R+E.

**Comment by mcnaugha** [comment]
I'm running macOS 12.2 (21D5025f) but I wouldn't have expected that to make a huge difference.

Also: 21.3.0 Darwin Kernel Version 21.3.0: Wed Dec  8 00:40:43 PST 2021; root:xnu-8019.80.11.111.1~1/RELEASE_ARM64_T6000 arm64


Here's what I see:

toybox-0.8.6 % LC_CTYPE=C make macos_defconfig

scripts/genconfig.sh
KCONFIG_ALLCONFIG=./kconfig/macos_miniconfig kconfig/conf -n Config.in > /dev/null

toybox-0.8.6 % LC_CTYPE=C make 
               
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe.............
Make generated/config.h from .config.
generated/flags.h sed: 2: "b single;:pair;h;n;:sin ...": undefined label 'pair;h;s/\([^ ]*\).*/\1 " "/;x'
sed: 2: "s/" *"//g;/^#/d;t clear ...": undefined label 'clear;:clear;s/"/"/p;t;s/\( [AB] \).*/\1 " "/p'
sed: 2: "s/" *"//g;/^#/d;t clear ...": undefined label 'clear;:clear;s/"/"/p;t;s/\( [AB] \).*/\1 " "/p'
make: *** [toybox] Error 1


LC_CTYPE=C was supposed to sort out the encoding issue. If I don't use it, now I get a load of errors. Too many to detail. 

Here are some samples:

    ^
toys/posix/xargs.c:87:22: error: use of undeclared identifier 'TT'
    if (entry) entry[TT.entries] = data;
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
clang: error: no such file or directory: 'generated/obj/main.o'


toys/posix/time.c:40:15: warning: 'vfork' is deprecated: Use posix_spawn or fork [-Wdeprecated-declarations]


Thanks.

**Comment by mcnaugha** [comment]
> Pushed the ARM M1 T8101 Build here https://github.com/xsscx/macos-research/blob/main/toybox/toybox-t8101-arm-built-macos_1162-landley_commit-4991ae7261671f00040c85a1c2d2eb39fd6a05ae.zip

This binary works. Thanks.

**Comment by enh-google** [comment]
oh, yeah, you need GNU sed (or toybox sed) to build toybox... this isn't a new issue with macOS 12 --- it's always been true. the homebrew sed works fine.

**Comment by xsscx** [comment]
Hey-

I too see that error on the Beta Train, probably more ABI issues...  I'll Build a macOS 12.x native arm build for toybox and update when I've got it Posted, probably CoB tomorrow US East.

Cheers!

**Comment by enh-google** [comment]
with gnu sed from homebrew:
```
~/toybox-12$ LC_CTYPE=C make macos_defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1 \
		-DPROJECT_NAME=\"ToyBox\"
scripts/genconfig.sh
KCONFIG_ALLCONFIG=./kconfig/macos_miniconfig kconfig/conf -n Config.in > /dev/null
~/toybox-12$ LC_CTYPE=C make
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe.............
Make generated/config.h from .config.
generated/flags.h generated/globals.h generated/tags.h generated/help.h
Compile toybox...........lib/portability.c:474:10: warning: unused variable 'offset' [-Wunused-variable]
  int i, offset;
         ^
1 warning generated.
..........................................................................................................
~/toybox-12$ 
```
with darwin sed:
```
~/toybox-12$ LC_CTYPE=C make macos_defconfig
cc -o kconfig/conf kconfig/conf.c kconfig/zconf.tab.c -DKBUILD_NO_NLS=1 \
		-DPROJECT_NAME=\"ToyBox\"
scripts/genconfig.sh
KCONFIG_ALLCONFIG=./kconfig/macos_miniconfig kconfig/conf -n Config.in > /dev/null
~/toybox-12$ LC_CTYPE=C make
scripts/make.sh
Generate headers from toys/*/*.c...
generated/newtoys.h Library probe.............
Make generated/config.h from .config.
generated/flags.h sed: 2: "b single;:pair;h;n;:sin ...": undefined label 'pair;h;s/\([^ ]*\).*/\1 " "/;x'
sed: 2: "s/" *"//g;/^#/d;t clear ...": undefined label 'clear;:clear;s/"/"/p;t;s/\( [AB] \).*/\1 " "/p'
sed: 2: "s/" *"//g;/^#/d;t clear ...": undefined label 'clear;:clear;s/"/"/p;t;s/\( [AB] \).*/\1 " "/p'
make: *** [toybox] Error 1
~/toybox-12$ 
```
but like i say, i'm pretty sure that's not a regression. there's a reason i have gnu sed installed :-)

**Comment by xsscx** [comment]
Apple SRD Build Note
-----
These were the changes made to toybox to get a Build for iOS:

macos_miniconfig
----
Removed CONFIG vi=y

Makefile
-----
Remove echo CONFIG_VI=y >> toybox-src/kconfig/macos_miniconfig

That will Build toybox for cryptex from Commit https://github.com/landley/toybox/commit/6cc6d5b0651f1eba689a9c6e6d53d4502334208b

My latest SRD DMG contains the latest toybox unstripped here https://github.com/xsscx/srd/blob/main/dmg/universal-srd-toybox-unstripped-commit-ea4748a7cbfa5e2f3ef188f917d4e5aeac70dd0f.dmg which contains the arm64e build for toybox unstripped.

**Comment by enh-google** [comment]
okay, so the vi build error is a different bug. (which i hadn't seen on macOS because it's not in the default config for macOS, but i'm surprised we haven't seen that on linux!) anyway, i've sent a patch for that to the list too.

as for the sed stuff... i note that we already have this in make.sh:
```
  # This long and roundabout sed invocation is to make old versions of sed
  # happy. New ones have '\n' so can replace one line with two without all
  # the branches and tedious mucking about with hyperspace.
  # TODO: clean this up to use modern stuff.
```
followed by what seems to be the fix for the macOS sed issues (basically "use more -e lines"). so i guess if we wanted to be able to bootstrap more easily, that's not insurmountable. but aiui rob would prefer to go the other way and just say "bootstrap from this toybox prebuilt" and delete these workarounds?

**Comment by enh-google** [comment]
(it looks like vi is currently broken at run-time too. i've also sent a patch for that to the list :-) )

**Comment by xsscx** [comment]
Added this Note to Issue tracker in SRD Repo https://github.com/apple/security-research-device/issues/34 for SRD Cohort and https://github.com/xsscx/srd/issues/7 for the xss.cx crew

**Comment by xsscx** [comment]
@enh-google @landley Thank you very much for Landing those other Updates. 

Tested Build on macOS 11.6.2 & 12.1 for X86_64 and M1 T8101

Posted a universal binary and cpu slices to https://github.com/xsscx/macos-research/tree/main/toybox for Commit https://github.com/landley/toybox/commit/e7e4229c059f4a45eaf0ff0cb0f228275e3e7772 if helpful to anyone.

Thank You!

**Comment by enh-google** [comment]
thanks for testing (and confirming that things are fixed again)!
